spring.datasource.url =jdbc:mysql://localhost:3306/recruitmentjob
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




#| Môi tr??ng | ddl-auto    | Lý do       |
#| ---------- | ----------- | ----------- |
#| DEV        | update      | Nhanh, ti?n |
#| TEST       | create-drop | Test s?ch   |
#| PROD       | validate    | An toàn     |
