package com.webjob.application.enums;

public enum OutboxEventType {
    SEND_EMAIL,
    FORGOT_PASSWORD,

    JOB_APPLY,
    JOB_ALERT,
    FOLLOW_COMPANY_JOB,

    JOB_INDEX_CREATED,
    JOB_INDEX_UPDATED,
    JOB_INDEX_DELETED,
    JOB_INDEX_RESTORED,
    JOB_INDEX_APPLIED_COUNT_INCREMENTED,
    JOB_INDEX_APPLICATION_WITHDRAWN,
    JOB_INDEX_VIEW_COUNT_INCREMENTED,

    COMPANY_INDEX_CREATED,
    COMPANY_INDEX_UPDATED,
    COMPANY_INDEX_DELETED,
    COMPANY_INDEX_RESTORED
}
